on:
  workflow_call: 
    secrets:
      SONAR_TOKEN:
        description: 'Token for SonarQube authentication'
        required: true
    inputs:
      SONAR_DOMAIN_NAME:
          description: 'Domain name of the SonarQube server'
          required: true
          type: string
      FETCH_DEPTH:
          required: false
          default: 0
          type: number
      ENABLE_COREPACK:
          description: 'Flag to determine if corepack should be enabled'
          required: false
          default: false
          type: boolean
      NODE_VERSION:
          description: 'Node version to run (example: 20.12.2)'
          required: false
          default: '20.12.2'
          type: string
      RUN_LINT_EXPORTER:
        description: 'Flag to determine if npm run lint-exporter should be executed'
        required: false
        default: true
        type: boolean
      RUN_STYLELINT_EXPORTER:
        description: 'Flag to determine if npm run stylelint-exporter should be executed'
        required: false
        default: true
        type: boolean

name: Scan project with SonarQube scanner
jobs:
  run-sonar-checks:
    name: Run sonar checks
    runs-on: ubuntu-24.04
    steps:  
    - uses: actions/checkout@v4
      with:
        fetch-depth: ${{ inputs.FETCH_DEPTH }}   
    
    - name: Generate sonar project name
      run: |
        printf "\nsonar.projectKey = ${{ github.repository_owner }}-${{ github.event.repository.name }}-${{ github.head_ref || github.ref_name }}" | sed s/'\/'/'-'/g >> sonar-project.properties
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.NODE_VERSION }}
    
    - name: Enable Corepack
      if: ${{ inputs.ENABLE_COREPACK }}
      run: corepack enable    
    
    - name: Install packages based on lock-file
      if: ${{ inputs.RUN_LINT_EXPORTER || inputs.RUN_STYLELINT_EXPORTER }}
      run: |
        if [ -f yarn.lock ]; then
          echo "Detected yarn.lock, using Yarn"
          yarn
        elif [ -f package-lock.json ]; then
          echo "Detected package-lock.json, using npm"
          npm install
        else
          echo "No lock file found. Defaulting to yarn."
          yarn
        fi
      
    - name: Get lint-exporter report
      if: ${{ inputs.RUN_LINT_EXPORTER }}
      run: |
        bash -c 'npm run lint-exporter || :'
    
    - name: Get stylelint-exporter report
      if: ${{ inputs.RUN_STYLELINT_EXPORTER }}
      run: |
        bash -c 'npm run stylelint-exporter || :'
    
    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@v4.2.1
      with:
        args: >
          -Dhttp.proxyPort=3129
          -Dhttps.proxyPort=3129
          -Dhttp.proxyHost=${{ inputs.SONAR_DOMAIN_NAME }}
          -Dhttps.proxyHost=${{ inputs.SONAR_DOMAIN_NAME }}
      env:
        HTTP_PROXY: https://${{ inputs.SONAR_DOMAIN_NAME }}:3129
        HTTPS_PROXY: https://${{ inputs.SONAR_DOMAIN_NAME }}:3129
        NO_PROXY: localhost,127.0.0.1
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: https://${{ inputs.SONAR_DOMAIN_NAME }}
    
    - name: SonarQube Quality Gate check
      id: sonarqube-quality-gate-check
      continue-on-error: true
      uses: sonarsource/sonarqube-quality-gate-action@v1.1.0
      timeout-minutes: 5
      env:
       SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
       SONAR_HOST_URL: https://${{ inputs.SONAR_DOMAIN_NAME }}
    
    - name: Get detailed SonarQube issues
      if: steps.sonarqube-quality-gate-check.outcome == 'failure'
      continue-on-error: false 
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        PROJECT_KEY=$(echo "${{ github.repository_owner }}-${{ github.event.repository.name }}-${{ github.head_ref || github.ref_name }}" | sed 's/\//-/g')
        curl -s -u $SONAR_TOKEN: "https://${{ vars.SONAR_DOMAIN_NAME }}/api/issues/search?componentKeys=${PROJECT_KEY}&resolved=no&ps=500" > sonar_issues.json
        
        total=$(jq -r '.total' sonar_issues.json)

        if [ "$total" -eq 0 ]; then
          echo "Quality Gate Check failed!"
          echo ""
          echo "Quality Gate exception list:"
          conditions_json=$(curl -s -u $SONAR_TOKEN: "https://${{ vars.SONAR_DOMAIN_NAME }}/api/qualitygates/project_status?projectKey=$PROJECT_KEY")

          echo "### Quality Gate Check failed!" >> $GITHUB_STEP_SUMMARY
          echo "#### Quality Gate exception list::" >> $GITHUB_STEP_SUMMARY
          echo "Metric | Actual Value | Comparator | Error Threshold" >> $GITHUB_STEP_SUMMARY
          echo "--- | --- | --- | ---" >> $GITHUB_STEP_SUMMARY

          echo "$conditions_json" | jq -r '
            .projectStatus.conditions[]
            | select(.status == "ERROR")
            | "\(.metricKey) | \(.actualValue) | \(.comparator) | \(.errorThreshold)"
          ' >> $GITHUB_STEP_SUMMARY
          exit 1
        fi

        echo "### Detailed SonarQube Issues" >> $GITHUB_STEP_SUMMARY
        echo "File | Line | Error type | Description" >> $GITHUB_STEP_SUMMARY
        echo "--- | --- | --- | ---" >> $GITHUB_STEP_SUMMARY
        jq -r '.issues[] | "\(.component) | \(.line) | \(.severity) | \(.message)"' sonar_issues.json | tee sonar_issues_summary.txt | tee -a $GITHUB_STEP_SUMMARY
      
        echo "Detailed issues summary:"
        cat sonar_issues_summary.txt
        exit 1